
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/_react_native_oh_tpl_react_native_hole_view/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

RNHoleViewProps::RNHoleViewProps(
    const PropsParserContext &context,
    const RNHoleViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    holes(convertRawProp(context, rawProps, "holes", sourceProps.holes, {})),
    animation(convertRawProp(context, rawProps, "animation", sourceProps.animation, {}))
      {}

} // namespace react
} // namespace facebook
