
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/_react_native_oh_tpl_react_native_hole_view/EventEmitters.h>
#include <react/renderer/components/_react_native_oh_tpl_react_native_hole_view/Props.h>
#include <react/renderer/components/_react_native_oh_tpl_react_native_hole_view/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char RNHoleViewComponentName[];

/*
 * `ShadowNode` for <RNHoleView> component.
 */
using RNHoleViewShadowNode = ConcreteViewShadowNode<
    RNHoleViewComponentName,
    RNHoleViewProps,
    RNHoleViewEventEmitter,
    RNHoleViewState>;

} // namespace react
} // namespace facebook
