export default class BuildProfile { 
	static readonly HAR_VERSION = '3.0.0-alpha4-0.0.1';
	static readonly BUILD_MODE_NAME = 'debug';
	static readonly DEBUG = true;
	static readonly TARGET_NAME = 'default';
	static readonly APP_NAME = 'Keys Example';
	static readonly BUNDLE_ID = 'com.example.rnkeys.dev';
	static readonly ANDROID_CODE = '50';
	static readonly PACKAGE_ID = 'com.example.rnkeys.dev';
}